name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user
          rm -rf app
          git clone https://github.com/neelk8s/deploy-web-app-on-AWS.git app
          cd app
          docker stop myapp || true
          docker rm myapp || true
          docker build -t myapp .
          docker run -d --name myapp -p 5000:5000 myapp
